version: '3.8' # Puedes eliminar la versión si quieres evitar la advertencia

services:
  whatzilla-back:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env # Monta el archivo .env en el contenedor
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql
      - redis
    env_file:
      - .env # Carga las variables de entorno desde el archivo .env

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=superpassword
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=whatzilla
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
