services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: whatzilla-back
    restart: always
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: production
      MYSQL_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - mysql
      - redis
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379"
    networks:
      - backend

volumes:
  mysql_data:
    driver: local
