version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000" # Mapea el puerto 3000 de la aplicación al puerto 80 del host
    environment:
      - NODE_ENV=production
      - MYSQL_HOST=mysql
      - MYSQL_USER=whatzilla_user
      - MYSQL_PASSWORD=Pvek2gI1Vb14
      - MYSQL_DATABASE=whatzilla_database
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Pvek2gI1Vb14
      MYSQL_DATABASE: whatzilla_database
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server"]

volumes:
  mysql_data:
