version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whatzilla-back
    restart: no
    ports:
      - "3000:3000"  # Puerto de la app
    environment:
      NODE_ENV: production
      MYSQL_HOST: mysql
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  # Contraseña del root
      MYSQL_DATABASE: ${DB_NAME}               # Base de datos por defecto
      MYSQL_USER: ${DB_USER}                   # Usuario adicional
      MYSQL_PASSWORD: ${DB_PASSWORD}           # Contraseña del usuario adicional
    ports:
      - "3306:3306"                            # Puerto MySQL
    volumes:
      - mysql_data:/var/lib/mysql              # Persistencia de datos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"                            # Puerto Redis
    volumes:
      - redis_data:/data                       # Persistencia de Redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
