name: CI/CD for Whatzilla-Back

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, backend]

    steps:
      # 1. Checkout del repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Build and Deploy Docker Containers
      - name: Deploy Containers with Docker Compose
        run: |
          cd /home/cantalupe/src/whatzilla-back
          docker compose down || true
          docker compose pull
          docker compose up -d --build

      # 3. Verificar los Logs de la Aplicación (opcional)
      - name: View Application Logs
        run: |
          docker logs whatzilla-back
