name: CI/CD for Whatzilla-Back

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, backend]
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
      - name: Clean Previous Docker Setup
        run: |
          cd /home/cantalupe/src/whatzilla-back
          docker compose down --volumes || true
          docker rmi whatzilla-back_app || true

      - name: Sync Files to Server
        run: |
          rsync -av --exclude=".git" --exclude=".env" $GITHUB_WORKSPACE/ /home/cantalupe/src/whatzilla-back/
        
      - name: Deploy Containers with Docker Compose
        run: |
          cd /home/cantalupe/src/whatzilla-back
          docker compose up -d --build

        - name: View Application Logs
        run: |
          docker logs whatzilla-back
