name: CI/CD for Whatzilla-Back

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, backend]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Sync Files to Server
        run: |
          rsync -av --exclude=".git" $GITHUB_WORKSPACE/ /home/cantalupe/src/whatzilla-back/

      - name: Deploy Containers with Docker Compose
        run: |
          cd /home/cantalupe/src/whatzilla-back
          docker compose down || true
          docker compose pull
          docker compose up -d --build

      - name: View Application Logs
        run: |
          docker logs whatzilla-back
